### ISSUE TITLE
Cannot add a sesame device due to errors.

### ISSUE THREAD

**Issue by dirablue** [CANDY-HOUSE/SesameSDK_Android_with_DemoApp#9]
hi @Jerming 

I faced this error during testing new SDK for Android.
Could you help me to solve this issue?

On simulator
1. failed to open an App

On Real Android Device
1. add a sesame device on Sample SDK
2. tap a device
3. it shows errors and never stop loading.
Testing Device: Android 10

2020-08-27 11:31:29.778 15123-15141/co.candyhouse.sesame2 W/BluetoothGatt: Unhandled exception in callback
    java.util.NoSuchElementException: Array contains no element matching the predicate.
        at co.candyhouse.sesame.deviceprotocol.SSM2OpCode$Companion.getByValue(:27)
        at co.candyhouse.sesame.deviceprotocol.SSM2OpCodeKt.toOpCode(:23)
        at co.candyhouse.sesame.deviceprotocol.SSM2ReceivePayload.<init>(:5)
        at co.candyhouse.sesame.ble.Sesame2.CHSesame2Device$mBluetoothGattCallback$1.onCharacteristicChanged(:370)
        at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:478)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:780)
        at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:41)
        at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:472)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:306)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
2020-08-27 11:31:29.839 15123-15141/co.candyhouse.sesame2 D/BluetoothGatt: onConnectionUpdated() - 

![Screenshot_20200827-114137](https://user-images.githubusercontent.com/708452/91378048-72444980-e85a-11ea-9fe2-841c15435621.jpg)

**Comment by Jerming** [comment]
Thanks for creating the issue.
Could you wait until the CHSesame2Status  become "readyToRegister" and try again ?

**Comment by dirablue** [comment]
@Jerming Hi Jerming. Thank you for your help !
Currently I'm changing the device to new one with new farmware. Let me try it when I get new device.
